eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
server:
  port: 8763
spring:
  application:
    name: Server2

feign:
  hystrix:
    enabled: true