eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    com.netflix.discovery: DEBUG
    com.netflix.eureka: DEBUG
server:
    port: 8762
spring:
  application:
    name: Server